### ISSUE TITLE
not working with django 1.10.1

### ISSUE THREAD

**Issue by soulraven** [yourlabs/django-cities-light#124]
Is not working with latest version of django 1.10.1
i get this error: 

`File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/cities_light/contrib/restframework3.py", line 27, in <module>
    from django.conf.urls import patterns, url, include
ImportError: cannot import name patterns
`

**Comment by max-arnold** [comment]
Probably related to #120

**Comment by clutcher** [comment]
"patterns" was deprecated since django 1.8. For fast fix just remove "patterns" module from import and change:

urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       )

to: 
    urlpatterns = url(r'^', include(router.urls)),

[restframework3.txt](https://github.com/yourlabs/django-cities-light/files/486959/restframework3.txt)

**Comment by max-arnold** [comment]
Fixed in #128
